call pathogen#infect()
" For colors follow this link:
" http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html
set nocompatible
syntax on
let $VIMHOME = $HOME."/.vim"

filetype on
filetype plugin on

let mapleader=','

""Normal set
set cursorline
set showmode
set history=1000
set undolevels=100
set ruler
set ic
set splitbelow
set splitright
set laststatus=2

" Keep 3 lines after/before the cursor
set so=3

" active mouse on terminal
set mouse=a

" Turn off swap files
set noswapfile
set nobackup
set nowb


" Move codeblocks
vnoremap < <gv
vnoremap > >gv

" Better copy&paste
set clipboard=unnamed

"Backspace fix in mac
set backspace=start,eol,indent

"Colorscheme changes
autocmd ColorScheme * hi Visual term=reverse cterm=reverse ctermfg=10 ctermbg=8 guibg=DarkGrey
autocmd ColorScheme * hi SpellBad ctermfg=160 ctermbg=8

"setlocal colorcolumn=81
autocmd ColorScheme * hi ColorColumn ctermbg=241 guibg=None ctermfg=NONE guifg=NONE
function! g:ToggleColorColumn()
    if &colorcolumn != ''
        setlocal colorcolumn&
    else
        setlocal colorcolumn=+1
    endif
endfunction

nnoremap <silent> <leader>c :call g:ToggleColorColumn()<CR>

set expandtab
au BufWinEnter * set autoindent|set ts=4|set sw=4
au BufWinEnter *.html,*.js,*.css,*.scss,*.scala,*.yml,*.less set ts=2|set sw=2
au BufWinEnter *.scss set filetype=css


""Number
set number
map <silent><F2> :set invnumber<CR>

"Shortcuts
noremap % v%
map <Leader>z u<CR>
map <Leader><Leader> $<CR>
""Sort lines
vmap <leader>s :sort u<CR>

""Autocomplete functions
autocmd FileType c set omnifunc=ccomplete#Complete
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd BufRead,BufNewFile *.md setlocal textwidth=80
autocmd BufRead,BufNewFile *.rst setlocal textwidth=80

if has("gui_running")
    colorscheme desertEx
    set cursorcolumn
else
    colorscheme desertEx
    "colorscheme default " hack to force the highlight group to be created
endif


set guitablabel=%M%t
map <silent><C-m> :tabnext<CR>
map <silent><C-k> :tabnext<CR>
map <silent><C-n> :tabprevious<CR>
map <silent><C-j> :tabprevious<CR>
map <silent><C-t> :tabnew<CR>

""TabLeader
vmap <leader>= :Tabularize /=<CR>
vmap <leader>: :Tabularize /:\zs<CR>

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#virtualenv#enabled = 1
let g:airline#extensions#tabline#enabled = 1

""Python
""let g:pymode = 1
let g:pymode_doc = 1
let g:pymode_doc_key = 'K'
let g:pymode_folding = 0

xmap <Leader>c <Plug>Commentary

augroup plugin_commentary
    au!
    au FileType python setlocal commentstring=#%s
    au FileType yml setlocal commentstring=#%s
    au FileType htmldjango setlocal commentstring={#\ %s\ #}
    au FileType puppet setlocal commentstring=#\ %s
augroup END

map <C-a> :TagbarToggle<CR>
vmap <C-a> :TagbarToggle<CR>

map <silent><C-r> :NERDTreeToggle <CR>
vmap <silent><C-r> :NERDTreeToggle <CR>

"" Set Home for the current file
map <C-ha :call CallHome()<CR>
vmap <C-h> :call CallHome()<CR>
function! CallHome()
    :cd %:p:h
    :pwd
endfunction

func! Develop()
    call tagbar#OpenWindow()
    call NERDTreeCWD()
    endfunc
command! -nargs=0 Develop call Develop()
" Add a full develop mode
map <C-x> :Develop<CR>
vmap <C-x> :Develop<CR>

func! DeleteTrailingWS()
    exe "normal mz"
    %s/\s\+$//ge
    exe "normal `z"
endfunc
"autocmd BufWrite *.py :call DeleteTrailingWS()
autocmd BufWritePre * :%s/\s\+$//e

""Ser/Kamailio or Opensips
let g:tagbar_type_ser = {
    \ 'ctagstype' : 'ser',
    \ 'kinds' : [
        \ 'a:Avp',
        \ 'r:routes',
    \ ]
\ }

let g:indentLine_color_term = 239
