name: Go

on:
  push:
    branches: [ main, master, Test ]
  pull_request:
    branches: [ main, master, Test]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set the value
      run: |
        echo "testCoverage=20" >> $GITHUB_ENV
        dd if=/dev/zero of=/opt/image bs=1M count=128
        mkfs.ext4 /opt/image
        sudo losetup -f --show /opt/image
        whoami
        sudo usermod -a -G root $(whoami)
        losetup -f --show /opt/image
